name: Azure Upload

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Install yarn
        run: npm i yarn
      - name: Install NPM Packages
        run: yarn install
      - name: Install gatsby-cli
        run: yarn add gatsby-cli
      - name: Build Gatsby App
        run: yarn build
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob upload-batch --account-name chxco -d '$web' -s public
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: az cdn endpoint purge --content-paths  "/*" --profile-name "chxco" --name "chxco"   --resource-group "chxco"
      # Azure logout
      - name: logout
        run: az logout
